/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "utils/menu.h"

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("Para executar informe o IP do servidor com o qual deseja se conectar. Ex.: %s 0.0.0.0\n", argv[0]);
		return 0;
	}

	host = argv[1];
	menu(host);
	
	return 0;
}
