/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIATURE_H_RPCGEN
#define _MINIATURE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers_to_calculate {
	int value1;
	int value2;
};
typedef struct numbers_to_calculate numbers_to_calculate;

struct square_root_number {
	int value;
};
typedef struct square_root_number square_root_number;

struct chat_message {
	char sender_username[30];
	char message[120];
	int id;
};
typedef struct chat_message chat_message;

#define MINIATURE_PROGRAM 0x20000001
#define CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  int * sum_1(numbers_to_calculate *, CLIENT *);
extern  int * sum_1_svc(numbers_to_calculate *, struct svc_req *);
#define subtraction 2
extern  int * subtraction_1(numbers_to_calculate *, CLIENT *);
extern  int * subtraction_1_svc(numbers_to_calculate *, struct svc_req *);
#define division 3
extern  int * division_1(numbers_to_calculate *, CLIENT *);
extern  int * division_1_svc(numbers_to_calculate *, struct svc_req *);
#define multiplication 4
extern  int * multiplication_1(numbers_to_calculate *, CLIENT *);
extern  int * multiplication_1_svc(numbers_to_calculate *, struct svc_req *);
#define square_root 5
extern  int * square_root_1(square_root_number *, CLIENT *);
extern  int * square_root_1_svc(square_root_number *, struct svc_req *);
#define send_message 6
extern  void * send_message_1(chat_message *, CLIENT *);
extern  void * send_message_1_svc(chat_message *, struct svc_req *);
#define get_messages 7
extern  chat_message * get_messages_1(char *, CLIENT *);
extern  chat_message * get_messages_1_svc(char *, struct svc_req *);
extern int miniature_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define subtraction 2
extern  int * subtraction_1();
extern  int * subtraction_1_svc();
#define division 3
extern  int * division_1();
extern  int * division_1_svc();
#define multiplication 4
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define square_root 5
extern  int * square_root_1();
extern  int * square_root_1_svc();
#define send_message 6
extern  void * send_message_1();
extern  void * send_message_1_svc();
#define get_messages 7
extern  chat_message * get_messages_1();
extern  chat_message * get_messages_1_svc();
extern int miniature_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers_to_calculate (XDR *, numbers_to_calculate*);
extern  bool_t xdr_square_root_number (XDR *, square_root_number*);
extern  bool_t xdr_chat_message (XDR *, chat_message*);

#else /* K&R C */
extern bool_t xdr_numbers_to_calculate ();
extern bool_t xdr_square_root_number ();
extern bool_t xdr_chat_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIATURE_H_RPCGEN */
