/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "miniature.h"

bool_t
xdr_numbers_to_calculate (XDR *xdrs, numbers_to_calculate *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_square_root_number (XDR *xdrs, square_root_number *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chat_message (XDR *xdrs, chat_message *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->sender_username, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->message, 120,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}
