/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../miniature.h"
#include "utils/operations.h"
#include "utils/logger.h"
#include "usecases/send_message_usecase.h"

int *sum_1_svc(numbers_to_calculate *argp, struct svc_req *rqstp)
{
	static int result;
	result = sum_operation(argp->value1, argp->value2);
	logger("Realizada uma operação de soma com resultado: %d", result);
	return &result;
}

int *subtraction_1_svc(numbers_to_calculate *argp, struct svc_req *rqstp)
{
	static int result;
	result = subtraction_operation(argp->value1, argp->value2);
	logger("Realizada uma operação de subtração com resultado: %d", result);
	return &result;
}

int *division_1_svc(numbers_to_calculate *argp, struct svc_req *rqstp)
{
	static int result;
	result = division_operation(argp->value1, argp->value2);
	logger("Realizada uma operação de divisão com resultado: %d", result);
	return &result;
}

int *multiplication_1_svc(numbers_to_calculate *argp, struct svc_req *rqstp)
{
	static int result;
	result = multiplication_operation(argp->value1, argp->value2);
	logger("Realizada uma operação de multiplicação com resultado: %d", result);
	return &result;
}

int *square_root_1_svc(square_root_number *argp, struct svc_req *rqstp)
{
	static int result;
	result = square_root_operation(argp->value);
	logger("Realizada uma operação de raíz quadrada com resultado: %d", result);
	return &result;
}

void *send_message_1_svc(chat_message *argp, struct svc_req *rqstp)
{
	static char result;
	client_send_message(*argp);
	logger("Nova mensagem enviada: %s disse \"%s\"", argp->sender_username, argp->message);
	return (void *)&result;
}

chat_message *get_messages_1_svc(char *argp, struct svc_req *rqstp)
{
	static chat_message result;

	return &result;
}
