/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../miniature.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
miniature_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		numbers_to_calculate sum_1_arg;
		numbers_to_calculate subtraction_1_arg;
		numbers_to_calculate division_1_arg;
		numbers_to_calculate multiplication_1_arg;
		square_root_number square_root_1_arg;
		chat_message send_message_1_arg;
		char get_messages_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case sum:
		_xdr_argument = (xdrproc_t) xdr_numbers_to_calculate;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sum_1_svc;
		break;

	case subtraction:
		_xdr_argument = (xdrproc_t) xdr_numbers_to_calculate;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) subtraction_1_svc;
		break;

	case division:
		_xdr_argument = (xdrproc_t) xdr_numbers_to_calculate;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) division_1_svc;
		break;

	case multiplication:
		_xdr_argument = (xdrproc_t) xdr_numbers_to_calculate;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) multiplication_1_svc;
		break;

	case square_root:
		_xdr_argument = (xdrproc_t) xdr_square_root_number;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) square_root_1_svc;
		break;

	case send_message:
		_xdr_argument = (xdrproc_t) xdr_chat_message;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) send_message_1_svc;
		break;

	case get_messages:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_chat_message;
		local = (char *(*)(char *, struct svc_req *)) get_messages_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MINIATURE_PROGRAM, CALCULATOR_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIATURE_PROGRAM, CALCULATOR_VERS, miniature_program_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MINIATURE_PROGRAM, CALCULATOR_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIATURE_PROGRAM, CALCULATOR_VERS, miniature_program_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MINIATURE_PROGRAM, CALCULATOR_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
